# name: build

# on:
#   push:

# jobs:
#   source-tarball:
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v2
#       - name: Create source tarball
#         if: startsWith(github.ref, 'refs/tags/')
#         run: |
#           package_utils/bundle-source.sh
